// Generates lib/content-data.ts by inlining the raw markdown of content/*.md.
// This removes runtime filesystem access (readdirSync/readFileSync), which the
// Cloudflare Workers runtime (unenv) does not implement. Run via npm scripts.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

function readDir(rel) {
  const dir = path.join(root, rel);
  const out = {};
  for (const file of readdirSync(dir).filter((f) => f.endsWith(".md"))) {
    out[file] = readFileSync(path.join(dir, file), "utf8");
  }
  return out;
}

export function generateContentData() {
  const problems = readDir("content/problems");
  const concepts = readDir("content/concepts");
  const body = `// AUTO-GENERATED by scripts/gen-content.mjs — do not edit.
// Raw markdown is inlined so content loads without runtime fs (Cloudflare Workers).
export const problemFiles: Record<string, string> = ${JSON.stringify(problems, null, 2)};

export const conceptFiles: Record<string, string> = ${JSON.stringify(concepts, null, 2)};
`;
  writeFileSync(path.join(root, "lib/content-data.ts"), body);
  return {
    problems: Object.keys(problems).length,
    concepts: Object.keys(concepts).length,
  };
}

// Allow running directly: `node scripts/gen-content.mjs`
if (import.meta.url === `file://${process.argv[1]}`) {
  const n = generateContentData();
  console.log(`generated lib/content-data.ts (${n.problems} problems, ${n.concepts} concepts)`);
}
